// react-version/src/components/TicketForm.jsx
import React, { useState } from 'react'
import { addDoc, collection, serverTimestamp } from 'firebase/firestore'
import { db } from '../firebase'

export default function TicketForm({onCreated}){
  const [title,setTitle]=useState('')
  const [desc,setDesc]=useState('')
  const [priority,setPriority]=useState('Low')

  const submit = async(e)=>{
    e.preventDefault()
    if(!title||!desc) return
    try{
      await addDoc(collection(db,'tickets'), {
        title, description: desc, priority, status:'open', createdAt: serverTimestamp()
      })
      setTitle(''); setDesc(''); setPriority('Low')
      onCreated && onCreated()
    }catch(err){ console.error(err); alert('Failed') }
  }
  return (
    <form onSubmit={submit} className="bg-white p-4 rounded shadow mb-6">
      <input className="input mb-2" placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)} />
      <textarea className="input mb-2" placeholder="Description" value={desc} onChange={e=>setDesc(e.target.value)} />
      <select className="input mb-2" value={priority} onChange={e=>setPriority(e.target.value)}>
        <option>Low</option><option>Medium</option><option>High</option>
      </select>
      <button className="btn-primary">Submit Ticket</button>
    </form>
  )
}

// vue-version/src/components/TicketForm.vue
<template>
  <form @submit.prevent="handleSubmit" class="space-y-3 p-6 border rounded shadow">
    <input v-model="title" type="text" placeholder="Ticket Title" class="w-full p-2 border rounded"/>
    <textarea v-model="description" placeholder="Description" class="w-full p-2 border rounded"></textarea>
    <select v-model="status" class="w-full p-2 border rounded">
      <option value="open">Open</option>
      <option value="in-progress">In Progress</option>
      <option value="closed">Closed</option>
    </select>
    <button type="submit" class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">
      Submit Ticket
    </button>
  </form>
</template>


<script setup>
import { ref } from 'vue'
import { db } from '@/firebase'
import { collection, addDoc, serverTimestamp } from 'firebase/firestore'

const title = ref('')
const description = ref('')
const status = ref('open')

const handleSubmit = async () => {
  try {
    await addDoc(collection(db, 'tickets'), {
      title: title.value,
      description: description.value,
      status: status.value,
      createdAt: serverTimestamp()
    })
    title.value = ''
    description.value = ''
    status.value = 'open'
    alert('Ticket created successfully!')
  } catch (err) {
    console.error(err)
    alert('Error creating ticket')
  }
}
</script>
