// vue-version/src/pages/Signup.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-100">
    <div class="bg-white p-8 rounded shadow w-full max-w-md">
      <h2 class="text-2xl font-bold mb-6 text-center">Sign Up</h2>
      <form @submit.prevent="handleSignup" class="space-y-4">
        <input v-model="email" type="email" placeholder="Email" class="w-full p-2 border rounded"/>
        <input v-model="password" type="password" placeholder="Password" class="w-full p-2 border rounded"/>
        <input v-model="confirmPassword" type="password" placeholder="Confirm Password" class="w-full p-2 border rounded"/>
        <button type="submit" class="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700">Sign Up</button>
      </form>
      <p class="mt-4 text-center text-gray-600">
        Already have an account? 
        <router-link to="/login" class="text-blue-600 hover:underline">Login</router-link>
      </p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { auth } from '@/firebase'
import { createUserWithEmailAndPassword } from 'firebase/auth'
import { useRouter } from 'vue-router'

const email = ref('')
const password = ref('')
const confirmPassword = ref('')
const router = useRouter()

const handleSignup = async () => {
  if (password.value !== confirmPassword.value) {
    alert("Passwords do not match")
    return
  }
  try {
    await createUserWithEmailAndPassword(auth, email.value, password.value)
    alert("Signup successful!")
    router.push('/dashboard')
  } catch (err) {
    console.error(err)
    alert(err.message)
  }
}
</script>

// react-version/src/pages/Signup.jsx
import React, { useState } from 'react'
import { createUserWithEmailAndPassword } from 'firebase/auth'
import { auth } from '../firebase'
import { useNavigate } from 'react-router-dom'

export default function Signup(){
  const [email,setEmail]=useState('')
  const [pass,setPass]=useState('')
  const nav = useNavigate()

  const submit=async(e)=>{
    e.preventDefault()
    try{
      await createUserWithEmailAndPassword(auth, email, pass)
      nav('/dashboard')
    }catch(err){
      alert(err.message)
    }
  }

  return (
    <div className="max-w-md mx-auto p-6">
      <h2 className="text-2xl mb-4">Sign up</h2>
      <form onSubmit={submit} className="space-y-4">
        <input className="input" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/>
        <input className="input" type="password" placeholder="Password" value={pass} onChange={e=>setPass(e.target.value)} required/>
        <button className="btn-primary w-full">Sign up</button>
      </form>
    </div>
  )
}
